---

- yum: name={{ item }}
  tags: yum
  with_items:
    - nagios
    - nagios-plugins-all
    - nagios-plugins-nrpe
    - nsca

- copy: src={{ item }} dest=/etc/nagios/conf.d/
  with_fileglob:
    - conf.d/*.cfg
  notify:
    - nagios check

- copy: src={{ item }} dest=/etc/nagios/objects/
  with_fileglob:
    - objects/*.cfg
  notify:
    - nagios check

- copy: src={{ item }} dest=/etc/nagios/ mode=600
  with_fileglob:
    - nsca.cfg
