---

- hosts: all
  gather_facts: no
  sudo: yes
  roles:
    - { role: common, tags: common }

- hosts: nagios_servers
  gather_facts: no
  sudo: yes
  roles:
    - { role: nagios, tags: nagios }

- hosts: target_servers
  gather_facts: no
  sudo: yes
  roles:
    - { role: nrpe, tags: nrpe }
